version: '3.8'

services:
  java_db:
    image: postgres:latest
    container_name: cvibe_db
    restart: unless-stopped
    environment:
       - POSTGRES_HOST=localhost
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
